// this is the first JavaScript program run when your Vue app is started
// think of it as the "main method" of your Vue application 
// it will instantiate an instance of Vue and cause the Vue home page (App.vue)
//    to be inserted into the index.html before it is sent to the browser
//
// there is pretty much no reason to ever change anything in the main.js generated by Vue create

import Vue from 'vue' // access to Vue stuff
import App from './App.vue' // access to Vue home page (App.vue)

Vue.config.productionTip = false // disable hints about Vue from App
//                                no longer needed - this is the default

new Vue({ // create an instance of Vue for the application
  render: h => h(App), // render: tells Vue what the main/home page component is called
  //                          must match the import name
}).$mount('#app') // .$mount() method tells Vue where in the index.html the components 
//                        should be added
//                    #app = html element with id="app"
