<template>
  <div>
    <h1>{{card.title}}</h1>
    <p>{{card.description}}</p>
    <comments-list 
    v-bind:comments="card.comments"/>
  </div>
</template>

<script>

import CommentsList from '../components/CommentsList';
import Service from '../services/BoardService'

export default {
  name: "card-detail",
  components: {
    CommentsList
  },
  data() {
    return {
      // properties of an individual card - values will come from API call
      card: {
        title: '',
        description: '',
        status: '',
        comments: []
      },
      // load the data from the API before the page is generated by Vue
      created() {
        // call the getCard() service to get the cards from the API
        Service.getCard(this.$route.params.boardID,
                        this.$route.params.cardID)
                        // wait for the API call to finish
                        .then(response => {
                          this.card = response // set the card property to response data
                        })
      }
    }
  }
}

// export default {
//   components: { CommentsList },
//   name: "card-detail"
// };
</script>
